global:
  scrape_interval: 10s
scrape_configs:
 - job_name: monitoring-delivery-service
   static_configs:
    - targets:
       - delivery-service:9400
 - job_name: monitoring-api-gateway
   static_configs:
    - targets:
       - api-gateway:9401
