openapi: 3.0.3
info:
  title: "Shipping on the Air API"
  description: |-
    This is the API of Shipping on the Air
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.3
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: account
    description: User account
  - name: delivery
    description: Ongoing delivery
  - name: user-session
    description: Logged in user session

paths:

  /accounts:
    post:
      tags:
        - account
      description: Create a new account
      operationId: createNewAccount
      parameters:
        - name: userName
          in: query
          description: user name
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: user password
          required: true
          schema:
            type: string
      responses:
        '200':
          description: account successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountId:
                    description: account id
                    type: string
                  loginLink:
                    description: link to do login
                    type: string
                  accountLink:
                    description: link to the account resource
                    type: string

  /accounts/{accountId}:
    get:
      tags:
        - account
      description: Get account info
      operationId: getAccountInfo
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

  /accounts/{accountId}/login:
    post:
      tags:
        - account
      description: User login
      operationId: login
      parameters:
        - name: accountId
          in: path
          description: ID of the account to return
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: user password
          required: true
          schema:
            type: string
      responses:
        '200':
          description: user successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    description: user session id
                    type: string
                  sessionLink:
                    description: link to user session resource
                    type: string
                  createDeliveryLink:
                    description: link to create a new delivery
                    type: string
                  trackDeliveryLink:
                    description: link to track a delivery
                    type: string

  /deliveries/{deliveryId}:
    get:
      tags:
        - delivery
      description: Get delivery info
      operationId: getDeliveryInfo
      parameters:
        - name: deliveryId
          in: path
          description: ID of the delivery to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
                
  /deliveries/{deliveryId}/{trackingSessionId}:
    get:
      tags:
        - delivery
      description: A user get the delivery status
      operationId: getDeliveryStatus
      parameters:
        - name: deliveryId
          in: path
          description: ID of the delivery
          required: true
          schema:
            type: string
        - name: trackingSessionId
          in: path
          description: ID of the tracking session
          required: true
          schema:
            type: string
      responses:
        '200':
          description: delivery status successfully obtained
          content:
            application/json:       
              schema:
                type: object
                properties:
                  schema:
                    $ref: '#/components/schemas/DeliveryStatus'
                
  /user-sessions/{sessionId}/create-delivery:
    post:
      tags:
        - user-session
      description: A logged in user creates a new delivery
      operationId: createNewDelivery
      parameters:
        - name: sessionId
          in: path
          description: ID of the user session
          required: true
          schema:
            type: string
        - name: weight
          in: query
          description: weight of the package to deliver
          required: true
          schema:
            type: number
        - name: startingPlace
          in: query
          description: the delivery starting place
          required: true
          schema:
            type: object
            properties:
              street:
                description: the delivery starting place street
                type: string
              number:
                description: the delivery starting place number
                type: number
        - name: destinationPlace
          in: query
          description: the delivery destination place
          required: true
          schema:
            type: object
            properties:
              street:
                description: the delivery destination place street
                type: string
              number:
                description: the delivery destination place number
                type: number
        - name: targetTime
          in: query
          description: the desired time to deliver the package
          required: true
          schema:
            type: object
            properties:
              year:
                description: the desired year to deliver the package
                type: number
              month:
                description: the desired month to deliver the package
                type: number
              day:
                description: the desired day to deliver the package
                type: number
              hours:
                description: the desired hour to deliver the package
                type: number
              minutes:
                description: the desired minute to deliver the package
                type: number
      responses:
        '200':
          description: delivery successfully created
          content:
            application/json:       
              schema:
                type: object
                properties:
                  deliveryId:
                    description: delivery identifier
                    type: string
                  deliveryLink:
                    description: link to the delivery resource 
                    type: string
                  trackDeliveryLink:
                    description: link to track the delivery
                    type: string
          
  /user-sessions/{sessionId}/track-delivery:
    post:
      tags:
        - user-session
      description: A logged in user tracks a delivery
      operationId: trackDelivery
      parameters:
        - name: sessionId
          in: path
          description: ID of the user session
          required: true
          schema:
            type: string
        - name: deliveryId
          in: query
          description: unique identifier of the delivery to track
          required: true
          schema:
            type: string
      responses:
        '200':
          description: delivery successfully tracked
          content:
            application/json:       
              schema:
                type: object
                properties:
                  trackingSessionId:
                    description: tracking session identifier
                    type: string
                  trackingSessionLink:
                    description: link to the tracking session resource
                    type: string

components:
  schemas:
    Account:
      type: object
      properties:
        userName:
          type: string
          description: user name
        password:
          type: string
          description: password of the user
        whenCreated:
          type: integer
          description: creation date/time (in millis)
          format: int64
    Delivery:
      type: object
      properties:
        deliveryId:
          type: string
          description: delivery identifier (unique)
        weight:
          type: number
          description: weight of the objects to deliver
        startingPlace:
          properties:
            street:
              description: the delivery starting place street
              type: string
            number:
              description: the delivery starting place number
              type: number
          description: the delivery starting place
        destinationPlace:
          properties:
            street:
              description: the delivery destination place street
              type: string
            number:
              description: the delivery destination place number
              type: number
          description: the delivery destination place
        targetTime:
          properties:
            year:
              description: the desired year to deliver the package
              type: number
            month:
              description: the desired month to deliver the package
              type: number
            day:
              description: the desired day to deliver the package
              type: number
            hours:
              description: the desired hour to deliver the package
              type: number
            minutes:
              description: the desired minute to deliver the package
              type: number
          description: the desired time to deliver the package
    DeliveryStatus:
      type: object
      properties:
        deliveryId:
          type: string
          description: delivery identifier (unique)
        status:
          type: string
          description: delivery status
          items:
            type: string
            enum:
              - TO SEND
              - SENT
              - ARRIVED
        timeLeft:
          type: string
          description: time left for the delivery to arrive
  