openapi: 3.0.3
info:
  title: "Shipping on the Air API - Delivery Service"
  description: |-
    This is the API of Shipping on the Air Delivery Service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.4
servers:
  - url: https://localhost:8080/api/v1 # TODO: change localhost
tags:
  - name: delivery
    description: Ongoing delivery
  - name: user-session
    description: Logged in user session

paths:
  /deliveries/{deliveryId}:
    get:
      tags:
        - delivery
      description: Get delivery info
      operationId: getDeliveryInfo
      parameters:
        - name: deliveryId
          in: path
          description: ID of the delivery to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
                
  /deliveries/{deliveryId}/{trackingSessionId}:
    get:
      tags:
        - delivery
      description: A user get the delivery status
      operationId: getDeliveryStatus
      parameters:
        - name: deliveryId
          in: path
          description: ID of the delivery
          required: true
          schema:
            type: string
        - name: trackingSessionId
          in: path
          description: ID of the tracking session
          required: true
          schema:
            type: string
      responses:
        '200':
          description: delivery status successfully obtained
          content:
            application/json:       
              schema:
                type: object
                properties:
                  schema:
                    $ref: '#/components/schemas/DeliveryStatus'

components:
  schemas:
    Delivery:
      type: object
      properties:
        deliveryId:
          type: string
          description: delivery identifier (unique)
        weight:
          type: number
          description: weight of the objects to deliver
        startingPlace:
          properties:
            street:
              description: the delivery starting place street
              type: string
            number:
              description: the delivery starting place number
              type: number
          description: the delivery starting place
        destinationPlace:
          properties:
            street:
              description: the delivery destination place street
              type: string
            number:
              description: the delivery destination place number
              type: number
          description: the delivery destination place
        expectedShippingMoment:
          properties:
            year:
              description: the desired year to deliver the package
              type: number
            month:
              description: the desired month to deliver the package
              type: number
            day:
              description: the desired day to deliver the package
              type: number
            hours:
              description: the desired hour to deliver the package
              type: number
            minutes:
              description: the desired minute to deliver the package
              type: number
          description: the desired time to deliver the package
    DeliveryStatus:
      type: object
      properties:
        deliveryId:
          type: string
          description: delivery identifier (unique)
        status:
          type: string
          description: delivery status
          items:
            type: string
            enum:
              - TO SEND
              - SENT
              - ARRIVED
        timeLeft:
          type: string
          description: time left for the delivery to arrive
  